const express = require("express");
const app = express();
const port = process.env.PORT || 3000;

/**
 * If the path is / or ends with a / redirect to index.html of the target
 * directory
 */
app.get("*", (req, _res, next) => {
  if (req.url === "/") {
    req.url += "index.html";
  } else if (req.url.endsWith("/")) {
    req.url += "index.html";
  }
  next();
});

app.use(express.static("public"));

/**
 * If the intended request does not match any existing files, redirect to 404
 * page generated by hugo.
 */
app.use((req, res, next) => {
  req.url = "/404/index.html";
  res.status = 404;
  next();
});
app.use(express.static("public"));

app.listen(port, () => {
  console.log(`Web server started on port ${port}`);
});
